gestion_vuelos/routes/auth.py
from datetime import date, datetime
from flask import Blueprint, request, session, render_template, redirect, url_for, flash, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.datastructures import ImmutableMultiDict
from gestion_vuelos.models.ModelUsuario import ModelUsuario

auth = Blueprint('auth', __name__, url_prefix='/auth')


@auth.route('/login', methods=["POST"])
def login():
    email = request.form.get("email")
    password = request.form.get("password")

    if email == None:
        flash("El correo es requerido", "error")
        return redirect(request.referrer)
    elif password == None:
        flash("La contraseña es requerida", "error")
        return redirect(request.referrer)

    password = str(password)

    user = ModelUsuario.obtener_por_correo_login(email)
    if user == None:
        flash("Credenciales incorrectas", "error")
        return redirect(request.referrer)
    elif user[1] != email or not check_password_hash(user[2], password):
        flash("Credenciales incorrectas", "error")
        return redirect(request.referrer)
    else:
        session.clear()
        session["user_id"] = user[0]
        session["user_nombre"] = user[3]
        return redirect(url_for("home.index"))


@auth.route('/registro/inicial', methods=["POST"])
def registro_inicial():
    session["nombre"] = request.form.get("nombre")
    session["apellido"] = request.form.get("apellido")
    session["email"] = request.form.get("email")
    session["password"] = request.form.get("password")
    return redirect(url_for("home.registro"))


@auth.route("/register", methods=["POST"])
def register():
    if not validate_register_data(request.form):
        return redirect(request.referrer)
    nombre = request.form.get("fname") or ""
    apellido = request.form.get("lname") or ""
    tipo_documento = int(request.form.get("tipoDocumento") or "")
    genero = request.form.get("genero") or ""
    identificacion = request.form.get("numeroIdentificacion") or ""
    fecha_de_nacimiento = datetime.fromisoformat(
        request.form.get("fechaNacimiento") or "")
    nacionalidad = int(request.form.get("nacionalidad") or "")
    correo = request.form.get("email") or ""
    password = generate_password_hash(request.form.get("password") or "")
    telefono = request.form.get("phone") or ""
    pais = int(request.form.get("country") or "")
    ciudad = int(request.form.get("city") or "")

    usuario = ModelUsuario.obtener_por_correo(correo)
    if usuario is None:
        ModelUsuario.agregar_usuario(tipo_documento, identificacion, nombre, apellido,
                                     fecha_de_nacimiento, ciudad, pais, genero, correo, password, telefono,
                                     nacionalidad, 3)
        flash("usuario registrado satisfactoriamente", "success")
    else:
        flash("El usuario ya existe", "error")

    return redirect(url_for("home.index"))


def validate_register_data(form: ImmutableMultiDict):
    validated = True
    if not form.get("fname"):
        flash("El nombre es requerido", "error")
        validated = False
    elif not form.get("lname"):
        flash("El apellido es requerido", "error")
        validated = False
    elif not form.get("tipoDocumento"):
        flash("El tipo de documento de identidad es requerido es requerido", "error")
        validated = False
    elif not form.get("genero"):
        flash("El género es requerido", "error")
        validated = False
    elif not form.get("numeroIdentificacion"):
        flash("El número de identificación es requerido", "error")
        validated = False
    elif not form.get("fechaNacimiento"):
        flash("La fecha de nacimiento es requerida", "error")
        validated = False
    elif not form.get("nacionalidad"):
        flash("La nacionalidad es requerida", "error")
        validated = False
    elif not form.get("email"):
        flash("El correo es requerido", "error")
        validated = False
    elif not form.get("email_confirm"):
        flash("Debe escribir nuevamente su correo", "error")
        validated = False
    elif form.get("email") != form.get("email_confirm"):
        flash("Los correos no coinciden", "error")
        validated = False
    elif not form.get("password"):
        flash("La contraseña es requerida", "error")
        validated = False
    elif not form.get("password_confirm"):
        flash("Debe escribir nuevamente su contraseña", "error")
        validated = False
    elif form.get("password") != form.get("password_confirm"):
        flash("Las contraseñas no coinciden", "error")
        validated = False
    elif not form.get("phone"):
        flash("El teléfono de contacto es requerido", "error")
        validated = False
    elif not form.get("address"):
        flash("La dirección es requerida", "error")
        validated = False
    elif not form.get("country"):
        flash("El país es requerido", "error")
        validated = False
    elif not form.get("city"):
        flash("La ciudad es requerida", "error")
        validated = False
    elif not form.get("contact"):
        flash("El nombre del contacto de emergencia es requerido", "error")
        validated = False
    elif not form.get("n_contact"):
        flash("El teléfono del contacto de emergencia es requerido", "error")
        validated = False
    elif not form.get("aceptar_politicas"):
        flash("Debe aceptar las políticas de privacidad", "error")
        validated = False
    return validated


@auth.route('/logout', methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("home.index"))


@auth.before_app_request
def load_logged_in_user():
    if session:
        user_id = session.get('user_id')
        if user_id is None:
            g.user = None
        else:
            g.user = ModelUsuario.obtener(user_id)

gestion_vuelos/routes/home.py
from flask import Blueprint, render_template, session

from gestion_vuelos.models.ModelPais import ModelPais
from gestion_vuelos.models.ModelCiudad import ModelCiudad
from gestion_vuelos.models.ModelTipoDocumento import ModelTipoDocumento
from gestion_vuelos.models.ModelNacionalidades import ModelNacionalidad

home = Blueprint('home', __name__)


@home.route('/')
def index():
    return render_template('index.html')


@home.route('/conocenos')
def about():
    return render_template('about.html')


@home.route('/destinos')
def travel():
    return render_template('travel.html')


@home.route("/reservas")
def reservas():
    return render_template('reservas.html')


@home.route("/ofertas")
def ofertas():
    return render_template('ofertas.html')


@home.route("/registro")
def registro():
    nombre = session.get("nombre") or ""
    apellido = session.get("apellido") or ""
    email = session.get("email", "") or ""
    password = session.get("password") or ""
    paises = ModelPais.get_paises()
    ciudades = ModelCiudad.get_ciudades()
    tiposDocumento = ModelTipoDocumento.get_tipos_documento()
    nacionalidades = ModelNacionalidad.get_nacionalidades()
    session.clear()
    return render_template('user_register.html', nombre=nombre, apellido=apellido, email=email, password=password, paises=paises, ciudades=ciudades, tiposDocumento=tiposDocumento, nacionalidades=nacionalidades)


@home.route('/contacto')
def contacto():
    return render_template('atencion_usuario.html')

gestion_vuelos/templates/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>{%block titulo%} {%endblock%} | Aeropuerto Alfonso Bonilla Aragon</title>
  <!-- Bootstrap CSS v5.2.0-beta1 -->
  <link rel="stylesheet"
    href="{{url_for('static', filename='node_modules/bootstrap-icons/font/bootstrap-icons.css')}}" />
  <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/stilos.css')}}">
  {%block styles%}
  {%endblock%}
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid flex-column flex-lg-row">
        <a class="navbar-brand" href="{{url_for('home.index')}}">
          <img src="{{url_for('static', filename='images/aeropuerto/logoaerocali.png')}}" width="60"
            alt="logo principal" />
          <span class="d-none d-lg-inline">AEROPUERTO <strong>ALFONSO BONILLA ARAGON</strong></span>
        </a>
        <ul class="nav ms-lg-auto">
          <!-- <div class="mx-auto" style="width: 700px;"></div> -->
          {% if session and 'user_nombre' in session %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              <i class="bi bi-person-circle"></i>
              Bienvenido, {{session['user_nombre']}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">cerrar sesión</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link nav-principal" href="#" id="dropdownId" data-bs-toggle="modal"
              data-bs-target="#login-modal">
              <i class="bi bi-person-circle"></i>
              iniciar sesión
            </a>
          </li>
          <div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="login-modal-title" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="login-modal-title">INICIAR SESIÓN</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                  <form id="login-form" method="POST" action="{{url_for('auth.login')}}">
                    <div class="mb-3">
                      <label for="username" class="col-form-label">USUARIO:</label>
                      <input type="email" class="form-control" id="username" name="email" required />
                    </div>
                    <div class="mb-3">
                      <label for="password" class="col-form-label">CONTRASEÑA:</label>
                      <input type="password" class="form-control" id="password" name="password" required />
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                  <button type="submit" form="login-form" class="btn btn-primary">INGRESAR</button>
                </div>
              </div>
            </div>
          </div>
          {% endif %}

        </ul>
        <form class="d-flex my-2 my-lg-0">
          <input class="form-control me-2" type="text" placeholder="Search">
          <button type="submit">BUSCAR</button>
        </form>
      </div>
    </nav>
    <!-- añadio sombra en el cabezote <div class="shadow p-3 mb-5 bg-body rounded"> -->
    <div class="shadow p-3 mb-5 bg-body rounded">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
          aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav w-90 justify-content-md-between mt-5 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link nav-principal" href="{{url_for('home.index')}}">
                INICIO </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-principal" href="{{url_for('home.about')}}">CONÓCENOS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-principal" href="{{url_for('home.travel')}}">VUELOS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-principal" href="{{url_for('home.registro')}}">REGISTRO</a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-principal" href="{{url_for('home.contacto')}}">ATENCIÓN AL USUARIO</a>
            </li>
        </div>
      </nav>
      </ul>
    </div>

  </header>
  <main class="container-fluid">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    {% for msg in errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
      {{msg}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {%block contenido%}
    {%endblock%}
  </main>
  <footer class="mt-4">
    <p class="text-center">AEROCALI</p>
    <p class="text-center">&copy; AEROPUERTO ALFONSO BONILLA ARAGON</p>

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">TÉRMINOS Y CONDICIONES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">POLÍTICAS DE PRIVACIDAD</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">POLÍTICA DE COOKIES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">MAPA DEL SITIO</a>
      </li>
    </ul>
    <div class="nav justify-content-evenly">
      <img src="{{url_for('static', filename='images/Grupo-11376@2x.png')}}" alt="" width="30" height="30" />
      <img src="{{url_for('static', filename='images/iconos/Logo-aeronautica.png')}}" height="30" alt="" />
      <i class="bi bi-facebook"></i>
      <i class="bi bi-instagram"></i>
      <i class="bi bi-twitter"></i>
    </div>

  </footer>
  <script src="{{url_for('static', filename='node_modules/@popperjs/core/dist/umd/popper.min.js')}}">
  </script>

  <script src="{{url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js')}}">
  </script>
  {%block js%}
  {%endblock%}
</body>

</html>

gestion_vuelos/templates/index.html
{%extends "base.html" %}
{%block titulo %}
Inicio
{%endblock%}
{%block contenido %}
<div class="row mb-3">
  <div class="col-sm-12 col-lg-6 mb-3 mb-lg-0">
    <h3>
      <span class="ps-5">AEROPUERTO</span><br>
      <span class="g">ALFONSO</span><br>
      <span class="m">BONILLA ARAGÓN</span>
    </h3>

    <p class="pjustify">El Aeropuerto Internacional Alfonso Bonilla Aragón (anteriormente llamado Aeropuerto
      Internacional de
      Palmaseca)
      (IATA: CLO, OACI: SKCL) localizado en el corregimiento de Palmaseca del municipio de Palmira, Valle del Cauca,
      Colombia, sirve a la ciudad de Cali. Fue inaugurado en 1971. En la actualidad, es el tercer aeropuerto de
      Colombia
      en movimiento de pasajeros, después del Aeropuerto El Dorado de la ciudad de Bogotá y el Aeropuerto
      Internacional
      José María Córdova de Medellín.
      Es la base para aviones privados y comerciales, además de ser la sede de la escuela de formación de pilotos
      Aeroccidente.</p>
    <a class="btn btn-primary btn-dob" href="{{url_for('home.about')}}"> CONÓCENOS </a>
  </div>
  <div class="col-sm-12 col-lg-6">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{url_for('static', filename='/images/aeropuerto/AIABA-Finales-39-2-scaled.jpg')}}"
            class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img
            src="{{url_for('static', filename='/images/aeropuerto/4-pasos-para-hacer-realidad-ese-viaje-que-no-has-podido-emprender.jpg')}}"
            class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{{url_for('static', filename='/images/aeropuerto/1561110509001.jpg')}}" class="d-block w-100"
            alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Siguiente</span>
      </button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 col-lg-6 mb-3 mb-lg-0">
    <form class="formulario-inicio p-4" method="POST" action="{{ url_for('auth.registro_inicial') }}">
      <fieldset>
        <legend>REGÍSTRATE AQUÍ</legend>
        <div class="row mb-3">
          <div class="col-sm-12 col-md-6 mb-3 mb-md-0">
            <input class="form-control" type="text" name="nombre" placeholder="Nombre">
          </div>
          <div class="col-sm-12 col-md-6">
            <input class="form-control" type="text" name="apellido" placeholder="Apellido">
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-12 col-md-6 mb-3 mb-md-0">
            <input type="email" class="form-control" name="email" placeholder="Correo Electronico">
          </div>
          <div class="col-sm-12 col-md-6 mb-3 mb-md-0">
            <input type="password" class="form-control" name="password" placeholder="Contraseña">
          </div>
        </div>
        <div class="row"><button type="submit" class="btn btn-primary btn-dob">REGISTRARSE </button></div>

      </fieldset>

    </form>
  </div>
  <div class="col-sm-12 col-lg-6">
    <div class="row">
      <div class="col"><img class="img-fluid"
          src="{{url_for('static', filename='images/aeropuerto/reserva_vuelo_gettyrf_1207226731_sankai_getty_images.jpg')}}"
          alt=""></div>
      <div class="col"><img class="img-fluid"
          src="{{url_for('static', filename='images/aeropuerto/finanzasalviajar.jpg')}}" alt=""></div>
    </div>
    <div class="row">
      <div class="btn-group" role="group" aria-label="Basic example">
        <a class="btn btn-primary text-bt-ligt" href="{{url_for('home.reservas')}}">
          <i class="bi bi-cart3"></i>
          RESERVAS
        </a>
        <a class="btn btn-dark text-bt-ligt" href="{{url_for('home.ofertas')}}">
          <i class="bi bi-tags-fill"></i>
          OFERTAS
        </a>
      </div>
    </div>
  </div>
</div>
{%endblock%}

gestion_vuelos/templates/travel.html
{% extends 'base.html' %}
{% block titulo %}
Vuelos
{% endblock titulo %}

{% block contenido %}

<div class="row mb-3">
  <div class="col-sm-12 col-lg-6 mb-3 mb-lg-0">
    <h3>
      <span class="m">CONOCE NUESTROS</span>
      <span class="g">DESTINOS</span><br>

    </h3>

    <p> Consigue tiquetes baratos para viajar donde quieras y haz que el cielo sea tu límite.
      Hay una gran variedad de tarifas, aerolíneas y destinos para que elijas el que más te conviene.
      Decide tu nueva aventura, compra tus vuelos a destinos y viaja con seguridad
      viviendo una experiencia única</p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
        class="bi bi-cart3" viewBox="0 0 16 16">
        <path
          d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
      </svg>&nbsp;<a class="text-bt-ligt" href="{{url_for('home.reservas')}}">RESERVAS </a></button>
  </div>
  <div class="col-sm-12 col-lg-6">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{url_for('static', filename='/images/aeropuerto/97.jpg')}}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{{url_for('static', filename='/images/aeropuerto/Airplane.png')}}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img
            src="{{url_for('static', filename='/images/aeropuerto/los-mejores-destinos-para-viajar-fin-de-ano.jpg')}}"
            class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12 col-lg-6">
    <div class="row row-cols-1 row-cols-md-3 g-2">
      <div class="col">
        <h5 class="bg-enc-text">CARTAGENA</h5>
        <div class="card h-100">
          <img src="{{url_for('static', filename='images/aeropuerto/bocagrande-desde-el-hotel.jpg')}}"
            class="card-img-top" alt="...">
          <div class="card-body">
            <small class="card-text">Cartagena es una de las ciudades más norteñas
              de Colombia,
              situada a lo largo de la costa del Caribe. Tiene una gran población de casi un millón de habitantes
              y es la quinta
              ciudad más grande del país. Encuentre todos los vuelos regulares a Cartagena con diferentes
              aerolíneas, donde
              puedes esperar de una de las más agradables y relajantes experiencias, tanto al reservar como cuando
              estás viajando.</small>
          </div>
        </div>
      </div>
      <div class="col">
        <h5 class="bg-enc-text">BOGOTA</h5>
        <div class="card h-100">
          <img src="{{url_for('static', filename='images/aeropuerto/bogota.jpg')}}" class="card-img-top" alt="...">
          <div class="card-body">
            <small class="card-text">
              Bogotá, un lugar popular lleno de cultura, edificios históricos y modernos centros de negocios y
              entretenimiento.
              La ciudad es mucho más que solo la capital del país. También es considerada una sede para la
              cultura, el deporte, el arte y los negocios. Además, ¡puedes conseguir promociones fantásticas en vuelos a
              Bogotá.</small>
          </div>
        </div>
      </div>
      <div class="col">
        <h5 class="bg-enc-text">MEDELLIN</h5>
        <div class="card h-100">
          <img src="{{url_for('static', filename='images/aeropuerto/medellin.jpg')}}" class="card-img-top" alt="...">
          <div class="card-body">
            <small class="card-text">Medellín es la segunda ciudad más grande de
              Colombia,
              lo que la hace muy popular con turistas y viajeros de negocios. Esta ciudad sudamericana es el hogar
              de 3.5
              millones de personas y ofrece una muy rica historia, con su propia revolución industrial y un
              crecimiento de
              arte y cultura durante el último siglo. Hoy, con un vuelo a Medellín de nuestras aerolíneas
              disponibles, puedes experimentar la belleza natural y la vibrante cultura de esta emocionante
              ciudad.</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d8154535.614887539!2d-78.11782086239091!3d3.654135521872846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1scolombia%20ciudades%20y%20capitales!5e0!3m2!1ses!2sco!4v1665074503212!5m2!1ses!2sco"
      width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy"
      referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
</div>
{%endblock%}